###
POST http://localhost:3100/api/v1/users/new-user HTTP/1.1
Content-Type: application/json

{
    "lastname": "test",
    "email": "e@test.com",
    "current_password": "user123"
}

###
GET http://localhost:3100/api/v1/users HTTP/1.1

###
GET http://localhost:3100/api/v1/users/6511ef0bee6fe705d6f02126 HTTP/1.1

###
PATCH http://localhost:3100/api/v1/users/6511ef0bee6fe705d6f02126 HTTP/1.1
Content-Type: application/json

{
    "firstname": "Test dos",
    "email": "elpepe@gmail.com"
}

###
DELETE http://localhost:3100/api/v1/users/6511ef0bee6fe705d6f02126 HTTP/1.1


###
POST http://localhost:3100/api/v1/services/new-service HTTP/1.1
Content-Type: application/json

{
    "service_name": "Servicio 1",
    "service_description": "lorem ipsum"
}


###
GET http://localhost:3100/api/v1/services HTTP/1.1


###
GET http://localhost:3100/api/v1/services/6515e1a252193b5b3f723e52 HTTP/1.1

###
PATCH http://localhost:3100/api/v1/services/6515e1a252193b5b3f723e52 HTTP/1.1
Content-Type: application/json

{
    "firstname": "Test dos",
    "email": "elpepe@gmail.com"
}


###
DELETE http://localhost:3100/api/v1/services/6515e1a252193b5b3f723e52 HTTP/1.1





###
POST http://localhost:3100/api/v1/auth/signin HTTP/1.1
Content-Type: application/json

{
    "firstname": "test",
    "lastname": "test",
    "email": "asd@test.com",
    "current_password": "asd"
}


###
POST http://localhost:3100/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "asd@test.com",
    "current_password": "asd"
}


###
GET http://localhost:3100/api/v1/auth/get-me/6511efa8ee6fe705d6f02128 HTTP/1.1