###
POST http://localhost:3100/api/v1/users/new-user HTTP/1.1
Content-Type: application/json

{
    "firstname": "test",
    "lastname": "test",
    "email": "asdfg@test.com",
    "current_password": "asd",
    "phone_number": "3053575021"
}

###
GET http://localhost:3100/api/v1/users HTTP/1.1

###
GET http://localhost:3100/api/v1/users/6511ef0bee6fe705d6f02126 HTTP/1.1

###
PATCH http://localhost:3100/api/v1/users/6511ef0bee6fe705d6f02126 HTTP/1.1
Content-Type: application/json

{
    "firstname": "Test dos",
    "email": "elpepe@gmail.com"
}

###
DELETE http://localhost:3100/api/v1/users/6540676abd1efdd6e2556d43 HTTP/1.1




###
POST http://localhost:3100/api/v1/auth/signin HTTP/1.1
Content-Type: application/json

{
    "firstname": "test",
    "lastname": "test",
    "email": "1234@test.com",
    "current_password": "1234",
    "phone_number": "123"
}


###
POST http://localhost:3100/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "1234@test.com",
    "current_password": "14"
}


###
GET http://localhost:3100/api/v1/auth/get-me/65406841de540f9ce591437d HTTP/1.1